### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lonyle** [mssun/pass-ios#1]
1. settings -> Git Server
  if Authentication is not chosen, crash
2. settings
 if PGP Key is not chosen, crash
3. In the "Password Store" main frame
 if PGP passphrase is not correct, crash
4. PGP Key URL support only https, not including http

**Comment by mssun** [comment]
- [x] settings -> Git Server
if Authentication is not chosen, crash
- [x] settings
if PGP Key is not chosen, crash
- [x] In the "Password Store" main frame
if PGP passphrase is not correct, crash
- [ ] PGP Key URL support only https, not including http

The last one is under investigating (with lower priority).

**Comment by mssun** [comment]
For HTTP URL:

See article:https://forums.developer.apple.com/thread/48979 (App Transport Security REQUIRED January 2017)

In essence, HTTPS is mandatory in Jan 2017,
