### ISSUE TITLE
Incorrect GPG pass phrase leads to crash

### ISSUE THREAD

**Issue by chrishawes** [mssun/pass-ios#19]
If your gpg pass phrase is incorrect, Pass crashes when trying to decrypt passwords.

Perhaps test and warn when setting up your keys.

**Comment by mssun** [comment]
Thank you for the report. This is an known issue. I will work on it later.

**Comment by chrishawes** [comment]
No problem at all… thanks for letting me test.

**Comment by mssun** [comment]
Fixed by commit: a2bcbe180462e971a93400dd06bb82f6d1b653ed
